pipeline {
    agent any

    environment {
        GIT_REPO = 'https://github.com/Dilip-Devopos/Guvi-TrendStore.git'
    }

    stages {
        stage('Clone Repo') {
            steps {
                git url: "${GIT_REPO}", branch: 'main'
            }
        }

                stage('Deploy to Kubernetes') {
            steps {
                script {
                    sh '''
                        cd Guvi-TrendStore/deployment_pipeline
                        echo "Deploying to Kubernetes..."
                        touch deployment.yaml
                    '''
                }
            }
        }
    }

    post {
        success {
            emailext(
                subject: "SUCCESS: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
                body: "Good news!\n\nThe Jenkins job '${env.JOB_NAME}' completed successfully.\nBuild URL: ${env.BUILD_URL}",
                to: "dilipbca99@gmail.com"
                
            )
        }

        failure {
            emailext(
                subject: "FAILURE: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
                body: "Unfortunately, the Jenkins job '${env.JOB_NAME}' has failed.\nBuild URL: ${env.BUILD_URL}",
                to: "dilipbca99@gmail.com"
            )
        }
    }
}